[package]
name = "Aoc25"
version = "0.1.0"
edition = "2024"

[dependencies]
array2d = "0.3.2"
good_lp = "1.14.2"
kiddo = "5.2.3"
paste = "1.0.15"
petgraph = "0.8.3"
rayon = "1.11.0"
seq-macro = "0.3.6"
throw = "0.1.7"
union-find = "0.4.3"
